# Generated by Django 4.2.1 on 2023-05-05 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activated')),
                ('entry_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Entry Status')),
                ('food_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Food Status')),
                ('student_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='Student Id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
